FROM ubuntu
LABEL AUTHOR=ashvedau
RUN apt -y update
RUN apt -y install curl gnupg2 ca-certificates lsb-release
RUN echo "deb http://nginx.org/packages/ubuntu lsb_release -cs nginx" \
    | tee /etc/apt/sources.list.d/nginx.list
RUN echo "deb http://nginx.org/packages/mainline/ubuntu lsb_release -cs nginx" \
    | tee /etc/apt/sources.list.d/nginx.list
RUN curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -
RUN apt -y install nginx
COPY ./index.html /var/www/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

