FROM ubuntu
LABEL AUTHOR=ashvedau

# install nginx
RUN apt -y update
RUN apt -y install curl gnupg2 ca-certificates lsb-release
RUN echo "deb http://nginx.org/packages/ubuntu lsb_release -cs nginx" \
    | tee /etc/apt/sources.list.d/nginx.list
RUN echo "deb http://nginx.org/packages/mainline/ubuntu lsb_release -cs nginx" \
    | tee /etc/apt/sources.list.d/nginx.list
RUN curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -

COPY index_ubuntu.html /var/www/html

# run nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
